### PR TITLE
qubes-dom0-update: prevent concurrent execution

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/6345

### CODE REVIEW

**Comment by alimirjamali** [comment]
Moved the condition block down after checking if the script is run with root privileges (as it requires access to /var/lock)

**Review by marmarek — CHANGES_REQUESTED** [review]
`--check-only` doesn't require root, and now it will fail. Maybe move the lock to /var/run/qubes (writable by the `qubes` group)? Or create a subdir in /var/lock (using systemd-tmpfiles) that is writable by the qubes group.

**Comment by alimirjamali** [comment]
> Maybe move the lock to /var/run/qubes (writable by the `qubes` group)

This is a better idea. I even have used `/tmp/appname.lock` for non-root processes in the past. Amended PR will come in a second.

**Comment by marmarek** [comment]
But there is still an issue - if the file was created by root, it won't be writable by the normal user. The /run/qubes dir has sgid bit set, so the group will be correct already, but the file won't be group-writable. Maybe adjust umask just for the time of opening the lock file? Or maybe open the lock for reading if already exists (to make it race-free, probably as a handling when opening for writing fails)?

**Comment by alimirjamali** [comment]
I think it would be better to create the lock only if user is root. check-only should not worry about concurrent execution.

**Comment by alimirjamali** [comment]
> Maybe adjust umask just for the time of opening the lock file? Or maybe open the lock for reading if already exists

I will implement both of the above approaches

**Review by marmarek — APPROVED** [review]

**Pull request merged**
